### PR TITLE
Solves issue#37 candis not running on docker

### PR DESCRIPTION
**Pull request by promehul**
###### Explanation About What Code Achieves:

  - It maps the redis layer which is running on the container instead of trying to find redis on the localhost.
  - After this candis is running normally on docker. I am able to create pipelines and do stuff.

###### Screenshots/GIFs:
image

###### Steps To Test:

  -Run it.

###### TODOs:

  - None

### CODE REVIEW

**Comment by promehul** [comment]
Tests on this PR failed with error messages "no environment variables set". I am not able to get what I did wrong !!

**Comment by rupav** [comment]
Don't worry of tests, after removing get-candis in previous commits, tests are bound to fail.

**Comment by promehul** [comment]
Then merge it if you find it correct!!

**Comment by achillesrasquinha** [comment]
I don't think this is a good idea of providing the service name as a default. It should be localhost.

**Comment by achillesrasquinha** [comment]
Your service name should be overriden by environment variables passed into your docker service.

**Comment by achillesrasquinha** [comment]
Closing this.

**Comment by promehul** [comment]
@achillesrasquinha  please check now if its what you asked for.

**Comment by rupav** [comment]
@promehul are you still facing that refresh problem - pipeline not saving in db on refreshing?

**Comment by promehul** [comment]
image
Its getting saved in db but it is not getting displayed ON REFRESH !! @rupav

**Comment by rupav** [comment]
just created a pipeline named 'pilot', logged out, logged in back pipeline is still present.
Refreshed, then logged in, and again found the pipeline correctly.
Screenshot from 2019-03-20 21-33-57

**Comment by rupav** [comment]
Please check again, and let us know. Install a screen recorder (like 'peek'), to record the flow of the app, and thus the error you are facing, post the gif here when you are done.

**Comment by promehul** [comment]
@rupav  are you running it on docker or using get_candis script?
I followed the same steps that you followed .

**Comment by rupav** [comment]
One error found in the flow so far, `forgot password` functionality. That's a seperate issue, because of Gmail auth of our mail server. Except this, try finding other issues in docker setup @promehul .
I am running it on docker @promehul using your changes.

**Comment by promehul** [comment]
If it is running all fine, then please merge my PR.

**Comment by promehul** [comment]
/home/harshit/Videos/Kazam_screencast_00000.mp4

**Comment by rupav** [comment]
found the discrepency, I copied your changes in docker branch of candis. Achilles had already done some work on that branch for docker setup, try making your changes on docker branch of candis, and then check.

**Comment by promehul** [comment]
test
@rupav  I did this

**Comment by rupav** [comment]
You have to open the existing file, not creating new. How can it create new with the same name, rather try opening the existing file.
All works fine then.

**Comment by rupav** [comment]
This is the correct behavior of the app, if pipe with same name exists, you cant create one, and thus the warning.

**Comment by rupav** [comment]
try clicking on 'open' instead of 'new' after refreshing the browser, once you have created 'qwerty' pipe.

**Comment by promehul** [comment]
Thanks @rupav

**Comment by promehul** [comment]
This has been open for 9 days. Any follow up? @rupav

**Comment by rupav** [comment]
Did you @promehul try running the pipeline on docker?
Are you able to populate the 'file' (by creating new file) with CEL files? If so, please explain how so. Refer Readme GIF, for checking how to run the pipeline.

**Pull request merged**
